[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "permit2/=lib/permit2/",
    "solady/=lib/the-compact/lib/solady/src/",
    "the-compact/=lib/the-compact/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
